version: "3.8"
services:

  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: bonjour
      PGDATA: /var/lib/postgresql/data
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - rso-sae410

  pgadmin4:
    image: elestio/pgadmin:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@email.com
      PGADMIN_DEFAULT_PASSWORD: bonjour
      PGADMIN_LISTEN_PORT: 8080
    ports:
      - "8080:8080"
    volumes:
      - ./servers.json:/pgadmin4/servers.json
    networks:
      - rso-sae410
    #api-licenses   

  app-api-licenses:
    build: ./app_api_licenses
    image: app_api_licenses:vFinale
    ports:
      - "5009:5009"
    volumes:
      - /home/user/Documents/api_license/FA_2_Licenses/app_api_licenses:/app_api_licenses
    networks:
      - rso-sae410

  app-test-licenses:
    build: ./app_test_licenses
    image: app_test_licenses:vFinale
    links:
      - app-api-licenses
    volumes:
      - /home/user/Documents/api_license/FA_2_Licenses/app_test_licenses:/app_test_licenses
    networks:
      - rso-sae410

  #api-ipam:

  app-api-ipam:
    build: ./app_api_ipam
    image: app_api_ipam:vFinale
    ports:
      - "5009:5009"
    volumes:
      - /home/user/Documents/api_iapam/FA_2_Ipam/app_api_ipam:/app_api_ipam
    networks:
      - rso-sae410

  app-test-ipam:
    build: ./app_test_ipam
    image: app_test_ipam:vFinale
    links:
      - app-api-ipam
    volumes:
      - /home/user/Documents/api_ipam/FA_2_Ipam/app_test_ipam:/app_test_ipam
    networks:
      - rso-sae410

networks:
  rso-sae410:
